// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/typed/cilium.io/v2alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeCiliumSubnetTopologies implements CiliumSubnetTopologyInterface
type fakeCiliumSubnetTopologies struct {
	*gentype.FakeClientWithList[*v2alpha1.CiliumSubnetTopology, *v2alpha1.CiliumSubnetTopologyList]
	Fake *FakeCiliumV2alpha1
}

func newFakeCiliumSubnetTopologies(fake *FakeCiliumV2alpha1) ciliumiov2alpha1.CiliumSubnetTopologyInterface {
	return &fakeCiliumSubnetTopologies{
		gentype.NewFakeClientWithList[*v2alpha1.CiliumSubnetTopology, *v2alpha1.CiliumSubnetTopologyList](
			fake.Fake,
			"",
			v2alpha1.SchemeGroupVersion.WithResource("ciliumsubnettopologies"),
			v2alpha1.SchemeGroupVersion.WithKind("CiliumSubnetTopology"),
			func() *v2alpha1.CiliumSubnetTopology { return &v2alpha1.CiliumSubnetTopology{} },
			func() *v2alpha1.CiliumSubnetTopologyList { return &v2alpha1.CiliumSubnetTopologyList{} },
			func(dst, src *v2alpha1.CiliumSubnetTopologyList) { dst.ListMeta = src.ListMeta },
			func(list *v2alpha1.CiliumSubnetTopologyList) []*v2alpha1.CiliumSubnetTopology {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v2alpha1.CiliumSubnetTopologyList, items []*v2alpha1.CiliumSubnetTopology) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
