// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by informer-gen. DO NOT EDIT.

package v2alpha1

import (
	context "context"
	time "time"

	apisciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	versioned "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/cilium/cilium/pkg/k8s/client/informers/externalversions/internalinterfaces"
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/client/listers/cilium.io/v2alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CiliumSubnetTopologyInformer provides access to a shared informer and lister for
// CiliumSubnetTopologies. Prefer using the type-safe variant (see [TypedCiliumSubnetTopologyInformer]).
type CiliumSubnetTopologyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() ciliumiov2alpha1.CiliumSubnetTopologyLister
}

// TypedCiliumSubnetTopologyInformer provides access to a shared informer and lister for
// CiliumSubnetTopologies, including the type-safe TypedInformer variant.
// It is a superset of CiliumSubnetTopologyInformer.
type TypedCiliumSubnetTopologyInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() CiliumSubnetTopologyIndexInformer
	Lister() ciliumiov2alpha1.CiliumSubnetTopologyLister
}

// CiliumSubnetTopologyIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type CiliumSubnetTopologyIndexInformer cache.TypedSharedIndexInformer[*apisciliumiov2alpha1.CiliumSubnetTopology]

// CiliumSubnetTopologyHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for CiliumSubnetTopology.
type CiliumSubnetTopologyHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apisciliumiov2alpha1.CiliumSubnetTopology]

// CiliumSubnetTopologyDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for CiliumSubnetTopology.
type CiliumSubnetTopologyDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apisciliumiov2alpha1.CiliumSubnetTopology]

// CiliumSubnetTopologyFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for CiliumSubnetTopology.
type CiliumSubnetTopologyFilteringHandler = cache.TypedFilteringResourceEventHandler[*apisciliumiov2alpha1.CiliumSubnetTopology]

// CiliumSubnetTopologyIndexers is a specialization of [cache.TypedIndexers] for CiliumSubnetTopology.
type CiliumSubnetTopologyIndexers = cache.TypedIndexers[*apisciliumiov2alpha1.CiliumSubnetTopology]

// DeletedCiliumSubnetTopology is a specialization of [cache.DeletedObject] for CiliumSubnetTopology.
type DeletedCiliumSubnetTopology = cache.DeletedObject[*apisciliumiov2alpha1.CiliumSubnetTopology]

type ciliumSubnetTopologyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewCiliumSubnetTopologyInformer constructs a new informer for CiliumSubnetTopology type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedCiliumSubnetTopologyInformer]).
func NewCiliumSubnetTopologyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewCiliumSubnetTopologyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedCiliumSubnetTopologyInformer constructs a new informer for CiliumSubnetTopology type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedCiliumSubnetTopologyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers CiliumSubnetTopologyIndexers) CiliumSubnetTopologyIndexInformer {
	return NewTypedCiliumSubnetTopologyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredCiliumSubnetTopologyInformer constructs a new informer for CiliumSubnetTopology type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredCiliumSubnetTopologyInformer]).
func NewFilteredCiliumSubnetTopologyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedCiliumSubnetTopologyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredCiliumSubnetTopologyInformer constructs a new informer for CiliumSubnetTopology type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredCiliumSubnetTopologyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers CiliumSubnetTopologyIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) CiliumSubnetTopologyIndexInformer {
	return NewTypedCiliumSubnetTopologyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewCiliumSubnetTopologyInformerWithOptions constructs a new informer for CiliumSubnetTopology type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedCiliumSubnetTopologyInformerWithOptions]).
func NewCiliumSubnetTopologyInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedCiliumSubnetTopologyInformerWithOptions(client, options)
}

// NewTypedCiliumSubnetTopologyInformerWithOptions constructs a new informer for CiliumSubnetTopology type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedCiliumSubnetTopologyInformerWithOptions(client versioned.Interface, options internalinterfaces.InformerOptions) CiliumSubnetTopologyIndexInformer {
	gvr := schema.GroupVersionResource{Group: "cilium.io", Version: "v2alpha1", Resource: "ciliumsubnettopologys"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apisciliumiov2alpha1.CiliumSubnetTopology](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CiliumV2alpha1().CiliumSubnetTopologies().List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CiliumV2alpha1().CiliumSubnetTopologies().Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CiliumV2alpha1().CiliumSubnetTopologies().List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.CiliumV2alpha1().CiliumSubnetTopologies().Watch(ctx, opts)
			},
		}, client),
		&apisciliumiov2alpha1.CiliumSubnetTopology{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *ciliumSubnetTopologyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedCiliumSubnetTopologyInformerWithOptions(client, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *ciliumSubnetTopologyInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *ciliumSubnetTopologyInformer) TypedInformer() CiliumSubnetTopologyIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisciliumiov2alpha1.CiliumSubnetTopology](f.factory.InformerFor(&apisciliumiov2alpha1.CiliumSubnetTopology{}, f.defaultInformer))
}

func (f *ciliumSubnetTopologyInformer) Lister() ciliumiov2alpha1.CiliumSubnetTopologyLister {
	return ciliumiov2alpha1.NewCiliumSubnetTopologyLister(f.Informer().GetIndexer())
}

// ToTypedCiliumSubnetTopologyInformer converts an untyped informer into a TypedCiliumSubnetTopologyInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *CiliumSubnetTopology. If that is not the case, calling type-safe methods of the returned
// TypedCiliumSubnetTopologyInformer leads to runtime panics. A safer alternative is to pass
// around a TypedCiliumSubnetTopologyInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedCiliumSubnetTopologyInformer(informer CiliumSubnetTopologyInformer) TypedCiliumSubnetTopologyInformer {
	if informer, ok := informer.(TypedCiliumSubnetTopologyInformer); ok {
		return informer
	}
	return &ciliumSubnetTopologyTypedInformerAdapter{informer}
}

type ciliumSubnetTopologyTypedInformerAdapter struct {
	CiliumSubnetTopologyInformer
}

func (a *ciliumSubnetTopologyTypedInformerAdapter) TypedInformer() CiliumSubnetTopologyIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apisciliumiov2alpha1.CiliumSubnetTopology](a.Informer())
}

// ToCiliumSubnetTopologyIndexInformer converts an untyped informer into a CiliumSubnetTopologyIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *CiliumSubnetTopology. If that is not the case, calling type-safe methods of the returned
// CiliumSubnetTopologyIndexInformer leads to runtime panics. A safer alternative is to pass
// around a CiliumSubnetTopologyIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToCiliumSubnetTopologyIndexInformer(informer cache.SharedIndexInformer) CiliumSubnetTopologyIndexInformer {
	if informer, ok := informer.(CiliumSubnetTopologyIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apisciliumiov2alpha1.CiliumSubnetTopology](informer)
}
