// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by client-gen. DO NOT EDIT.

package v2alpha1

import (
	context "context"

	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	scheme "github.com/cilium/cilium/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// CiliumSubnetTopologiesGetter has a method to return a CiliumSubnetTopologyInterface.
// A group's client should implement this interface.
type CiliumSubnetTopologiesGetter interface {
	CiliumSubnetTopologies() CiliumSubnetTopologyInterface
}

// CiliumSubnetTopologyInterface has methods to work with CiliumSubnetTopology resources.
type CiliumSubnetTopologyInterface interface {
	Create(ctx context.Context, ciliumSubnetTopology *ciliumiov2alpha1.CiliumSubnetTopology, opts v1.CreateOptions) (*ciliumiov2alpha1.CiliumSubnetTopology, error)
	Update(ctx context.Context, ciliumSubnetTopology *ciliumiov2alpha1.CiliumSubnetTopology, opts v1.UpdateOptions) (*ciliumiov2alpha1.CiliumSubnetTopology, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*ciliumiov2alpha1.CiliumSubnetTopology, error)
	List(ctx context.Context, opts v1.ListOptions) (*ciliumiov2alpha1.CiliumSubnetTopologyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *ciliumiov2alpha1.CiliumSubnetTopology, err error)
	CiliumSubnetTopologyExpansion
}

// ciliumSubnetTopologies implements CiliumSubnetTopologyInterface
type ciliumSubnetTopologies struct {
	*gentype.ClientWithList[*ciliumiov2alpha1.CiliumSubnetTopology, *ciliumiov2alpha1.CiliumSubnetTopologyList]
}

// newCiliumSubnetTopologies returns a CiliumSubnetTopologies
func newCiliumSubnetTopologies(c *CiliumV2alpha1Client) *ciliumSubnetTopologies {
	return &ciliumSubnetTopologies{
		gentype.NewClientWithList[*ciliumiov2alpha1.CiliumSubnetTopology, *ciliumiov2alpha1.CiliumSubnetTopologyList](
			"ciliumsubnettopologies",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *ciliumiov2alpha1.CiliumSubnetTopology { return &ciliumiov2alpha1.CiliumSubnetTopology{} },
			func() *ciliumiov2alpha1.CiliumSubnetTopologyList { return &ciliumiov2alpha1.CiliumSubnetTopologyList{} },
		),
	}
}
