// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Cilium

// Code generated by lister-gen. DO NOT EDIT.

package v2alpha1

import (
	ciliumiov2alpha1 "github.com/cilium/cilium/pkg/k8s/apis/cilium.io/v2alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// CiliumSubnetTopologyLister helps list CiliumSubnetTopologies.
// All objects returned here must be treated as read-only.
type CiliumSubnetTopologyLister interface {
	// List lists all CiliumSubnetTopologies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*ciliumiov2alpha1.CiliumSubnetTopology, err error)
	// Get retrieves the CiliumSubnetTopology from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*ciliumiov2alpha1.CiliumSubnetTopology, error)
	CiliumSubnetTopologyListerExpansion
}

// ciliumSubnetTopologyLister implements the CiliumSubnetTopologyLister interface.
type ciliumSubnetTopologyLister struct {
	listers.ResourceIndexer[*ciliumiov2alpha1.CiliumSubnetTopology]
}

// NewCiliumSubnetTopologyLister returns a new CiliumSubnetTopologyLister.
func NewCiliumSubnetTopologyLister(indexer cache.Indexer) CiliumSubnetTopologyLister {
	return &ciliumSubnetTopologyLister{listers.New[*ciliumiov2alpha1.CiliumSubnetTopology](indexer, ciliumiov2alpha1.Resource("ciliumsubnettopology"))}
}
